### ISSUE TITLE
getting error in build_train_loader

### ISSUE THREAD

**Issue by farhadi76m** [NazirNayal8/RbA#5]
I wanted to train this model in a single GPU (Google Colab), but I've gotten this error! while I settled the --gpu_num 1  and also I changed the number of workers to either 0 and 1 , but it didn't work ! I faced with this error : 

`Traceback (most recent call last):
  File "/content/RbA/train_net.py", line 396, in <module>
    launch(
  File "/content/detectron2/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "/content/RbA/train_net.py", line 384, in main
    trainer = Trainer(cfg)
  File "/content/detectron2/detectron2/engine/defaults.py", line 378, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/content/RbA/train_net.py", line 175, in build_train_loader
    return build_detection_train_loader(cfg, mapper=mapper)
  File "/content/detectron2/detectron2/config/config.py", line 208, in wrapped
    return orig_func(**explicit_args)
  File "/content/detectron2/detectron2/data/build.py", line 549, in build_detection_train_loader
    return build_batch_data_loader(
  File "/content/detectron2/detectron2/data/build.py", line 339, in build_batch_data_loader
    data_loader = torchdata.DataLoader(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 238, in __init__
    assert prefetch_factor > 0
TypeError: '>' not supported between instances of 'NoneType' and 'int'`

moreover I just downloaded cityscapes dataset and have ran your sample command in help . could you help me what's my mistake ? 
thank you

**Comment by NazirNayal8** [comment]
Apologies for not having enough bandwidth at the time to resolve this issue. I am closing it but if needed it may be reopened.
